### ISSUE TITLE
Debería hacerse un shuffle de los jugadores al inciar la partida

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/backend#110]
El jugador que comienza con el turno se escoge de forma aleatoria, pero estaría bien que también se hiciese shuffle de los jugadores de una partida una vez comienza para que el orden no sea siempre el de unirse a la partida.

**Comment by xzebra** [comment]
Yo creo que el orden de unirse a partida es suficiente, no importa empezar antes o despues

**Comment by marioortizmanero** [comment]
Bueno si no es tan importante cierro esto
