### ISSUE TITLE
Gestión de monedas y tienda de mejoras

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/backend#12]

**Comment by xzebra** [comment]
Actualmente nuestro modelo de compras es el siguiente:
```python
class Purchase(db.Model):
    """
    Una compra realizada por un usuario en la tienda.
    """

    item_id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.Enum(PurchasableType), nullable=False, primary_key=True)

    # Relación "Many to One" (N:1)
    user_id = db.Column(
        db.String, db.ForeignKey("user.email", ondelete="CASCADE"), primary_key=True
    )
```
pero en los assets se almacenan simplemente nombre y ruta. No hay forma de hayar la correspondencia entre objetos e ids.

Se podrían hacer varias cosas:
- Almacenar en la BBDD los items para buscar en ellos y obtener el ID
- Indicar en los ficheros de assets el ID de cada objeto (puede llevar a problemas de consistencia de IDs)
- Ambas (para no tener que buscar IDs y evitar IDs repetidos o usados anteriormente) -> no será tan sencillo como ahora que el resto de integrantes del grupo añadan imágenes y tableros

**Comment by marioortizmanero** [comment]
Lo de la tienda no lo tenía muy decidido, pero el plan era usar simplemente los índices de las listas como los IDs. Realmente solo necesitamos eso y el número de monedas que cuesta, por lo que no creo que haga falta usar la BBDD para esto.

Dije lo de los índices de las listas para que fuera más sencillo gestionar los IDs, pero se pueden incluir en el JSON de forma explícita si hace falta. El formato JSON respeta el orden, así que no es un problema con los parsers de ningún lenguaje: https://stackoverflow.com/a/41794111/11488352

**Comment by xzebra** [comment]
> Usando los índices no solo nos evitamos problemas de consistencia

Me refería a casos como eliminar un objeto de la tienda (y no usar su mismo id), aunque no está en los requisitos y se podría simplificar con lo de los índices.

**Comment by marioortizmanero** [comment]
Claro no se hasta que punto hace falta eso. En todo caso pondria un booleano de `disabled` o `enabled` y ya, porque sino los que ya lo tuviesen comprado darían problemas.
