### ISSUE TITLE
Soporte para animaciones

### ISSUE THREAD

**Issue by xzebra** [UNIZAR-30226-2021-07/backend#123]
Habra que modificar el `game_update` en caso de que los frontends quieran implementar algun sistema de animaciones para las cartas o alguna forma de mostrar la carta que se acaba de jugar, por ejemplo mostrandola encima del monton de descartes; vendria bien para saber que tratamiento se acaba de jugar, por ejemplo.

Esto se sale fuera de la planificacion y es un añadido en caso de que nos sobre tiempo y ganas.

**Comment by marioortizmanero** [comment]
Posiblemente me coma mis palabras pero esto debería ser relativamente fácil si lo hacemos de la siguiente manera:

Si en los métodos de `GameUpdate` que combinan dos `GameUpdate`, como `merge_update`, `add` o `repeat` en vez de juntarlos en el mismo diccionario se lo añaden a una pila interna de diccionarios, luego tenemos una secuencia de todos los cambios al juego y al enviarlo podemos hacerlo de uno en uno. Enviando mensajes más pequeños se podrán tener animaciones sin problemas.

**Comment by marioortizmanero** [comment]
Pero vamos esto depende de lo bien que vayan los de frontend y si lo acaban haciendo. Por el momento se puede quedar así que es más simple.
