### ISSUE TITLE
Otro jugador puede ganar por un transplante

### ISSUE THREAD

**Issue by xzebra** [UNIZAR-30226-2021-07/backend#164]
Me he dado cuenta también de que hemos pasado por alto el caso del transplante entre un órgano sano y otro infectado, porque sí que puede hacer que gane otro jugador que no seas tú.

_Originally posted by @xzebra in https://github.com/UNIZAR-30226-2021-07/backend/issues/163#issuecomment-845920962_

**Comment by marioortizmanero** [comment]
Ok osea tendriamos que cambiar esto para que lo haga con todos los jugadores y ya, no? https://github.com/UNIZAR-30226-2021-07/backend/blob/master/gatovid/game/__init__.py#L286
