### ISSUE TITLE
Estadísticas no están protegidas

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/backend#42]
El endpoint de `/user_stats` no está protegido con `@jwt_required`. Y el email debería obtenerse con el token, no como parámetro, porque por el momento solo se pueden acceder a las estadísticas propias.

**Comment by xzebra** [comment]
El endpoint de estadísticas no tiene información sensible y no importa exponerlo. Además viene bien por si en un futuro se quiere mostrar las estadísticas de otros jugadores.

**Comment by xzebra** [comment]
No se usa el email para nada en las estadísticas, se usa el nombre de usuario (también para no exponer el email) para que se puedan consultar las estadísticas de cualquier usuario.
