### ISSUE TITLE
Gestión de estadísticas

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/backend#5]
- [ ] Partidas totales
- [ ] Partidas ganadas
- [ ] Partidas perdidas
- [ ] Horas de juego

**Comment by xzebra** [comment]
Esto realmente está hecho porque la clase y todo está definido.

**Comment by xzebra** [comment]
Lo único que quedaría sería poner `wins++` cuando ya se tengan las partidas.

**Comment by marioortizmanero** [comment]
Si, es que esto es más para cuando el juego esté hecho de todos modos. Habrá que guardarse también un timestamp de entrada a la partida para el tiempo de juego pero eso es todo.
