### ISSUE TITLE
Formato del código de la partida

### ISSUE THREAD

**Issue by jmarindiez** [UNIZAR-30226-2021-07/backend#68]
Habria que prohibir algunas letras que pueden ser confusas en los códigos.

Por ejemplo las O y 0 (cero) o las I (i mayuscula) y l (l minuscula).

Esto seria sobre todo para cuando se comparte el codigo de palabra y no mediante copia y pega

**Comment by marioortizmanero** [comment]
Pero que te crees que es un juego decente esto y todo o que

**Comment by jmarindiez** [comment]
Perdona, pero estaba con los panas echando una partida en el parque y no habia manera de conectarse porque confundo las ies con las eles
