### ISSUE TITLE
Gestión partidas privadas

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/backend#8]
- [x] Crear partida: el servidor le asigna una partida (nadie más podrá crear una partida con ese código hasta que acabe, **ojo con la concurrencia**). **El servidor tiene que saber quién es el creador de la partida (en privadas).**
- [x] Unirse a partida: consulta si es posible + `join_room`. Podría hacer falta inicialización o algo.
- [x] Abandonar partida
- [x] Empezar partida: solo el creador o lider puede.
- [x] Número de conectados: cada vez que se une o se va un usuario mientras se está creando la partida, se le informa a los clientes (para que sepan cuantos faltan por conectarse).

### Cuestiones
- [x] ¿Qué pasa si el lider se va mientras la creación de la partida? ¿Se debería delegar su cargo a otro lider o cancelar la creación?

**Comment by xzebra** [comment]
Hola, necesito que alguien me responda a esto para poder implementarlo:
>  ¿Qué pasa si el lider se va mientras la creación de la partida? ¿Se debería delegar su cargo a otro lider o cancelar la creación?

@UNIZAR-30226-2021-07/app @UNIZAR-30226-2021-07/web @UNIZAR-30226-2021-07/backend

**Comment by marioortizmanero** [comment]
Yo creo que tendría más sentido que se elija un nuevo líder aleatorio y ya no? Porque el líder sólo sirve al principio cuando se está configurando el juego no?

**Comment by xzebra** [comment]
Si, estoy poniendo el caso en el que se esta preparando la partida y es el lider el que elige cuando comenzar, y de repente el lider se desconecta.

**Comment by xzebra** [comment]
Yo tambien habia pensado que lo mas intuitivo era que se escogiera otro lider, pero queria vuestra opinion porque como deciamos que las partidas privadas son principalmente para ser jugadas entre amigos, si se desconectaba el lider igual era por algo inesperado y venia bien simplemente esperar a que se volviera a unir o que se cancelase la creacion de la partida.

**Comment by jmarindiez** [comment]
Yo le daba el "poder" a otro de la sala. Si se quiere volver a conectar que lo haga con el codigo compartido.

**Comment by marioortizmanero** [comment]
Es que como tal no se hasta que punto hace falta un líder. Crea la partida y es como uno más, pero no tiene acceso especial a nada.

**Comment by xzebra** [comment]
Hombre que no, basicamente puede empezar la partida y el resto no

**Comment by marioortizmanero** [comment]
Cierto no tuve en cuenta eso

**Comment by xzebra** [comment]
Vale pues, en cuanto reciba un par de opiniones más sobre lo de delegar el cargo de lider, lo implemento

**Comment by xzebra** [comment]
Cuando un lider se sale de la partida, se escoge un nuevo lider y se le envia un mensaje de tipo `game_owner`.

**Comment by Leticia-23** [comment]
Me parece correcto, porque supongo que lo dices porque alguien me tiene que dar a empezar, que es el momento en el que nadie más se podría unir. Pero a la hora de los clientes que implica recibir ese mensaje, o más bien cómo lo recibimos para poder dar la opción de empezar una partida si realmente no la has creado tú y la navegación "normal" no contaría con eso.

**Comment by xzebra** [comment]
cuando recibes un mensaje de tipo game_owner, tendrias que sustituir el popup de esperar partida de los jugadores por el popup con el botón de inciar partida
